/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Model.Parkir;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Dwinanda
 */
public class KeluarParkir extends javax.swing.JPanel {

    /**
     * Creates new form KeluarParkir
     */
    private JScrollPane contentScrollPane;
    private TableRowSorter<DefaultTableModel> rowSorter;

    /**
     * Creates new form LoginCivitas
     */
    public KeluarParkir(JScrollPane contentScrollPane) throws SQLException {

        this.contentScrollPane = contentScrollPane;
        initComponents();
        loadTableData();

        // Set up the row sorter for the table
        DefaultTableModel model = (DefaultTableModel) keluarTable.getModel();
        rowSorter = new TableRowSorter<>(model);
        keluarTable.setRowSorter(rowSorter);

        // Add a document listener to the search field
        searchField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }
        });
    }

    private void filterTable() {
        String text = searchField.getText();
        if (text.trim().length() == 0) {
            rowSorter.setRowFilter(null);
        } else {
            rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }

    private void loadTableData() {
        DefaultTableModel dtm = (DefaultTableModel) keluarTable.getModel();
        // Refresh table
        dtm.setRowCount(0);

        try {
            List<Parkir> parkirList = Database.getInstance().dataTable();

            // Populate the table
            for (Parkir p : parkirList) {
                dtm.addRow(new Object[]{
                    p.getNama(),
                    p.getNomorKendaraan(),
                    p.getWaktuMasuk(),
                    p.getCivitas(),
                    p.getJenisKendaraan()
                });
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        berandaAdminButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keluarTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        adminButton = new javax.swing.JButton();
        selesaiParkirButton = new javax.swing.JButton();
        hapusParkirButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 255, 243));

        berandaAdminButton.setBackground(new java.awt.Color(0, 0, 0));
        berandaAdminButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        berandaAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        berandaAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet.gif"))); // NOI18N
        berandaAdminButton.setText("Beranda");
        berandaAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaAdminButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "List Tabel Parkir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N

        keluarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Nomor Kendaraan", "Jam Masuk"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        keluarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(keluarTable);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Silakan klik sesuai di tabel kolom nomor kendaraan yang ingin keluar dari parkir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminButton.setBackground(new java.awt.Color(0, 0, 0));
        adminButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/r11.png"))); // NOI18N
        adminButton.setText("Admin");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        selesaiParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        selesaiParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        selesaiParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        selesaiParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g11.png"))); // NOI18N
        selesaiParkirButton.setText("Selesai Parkir");
        selesaiParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiParkirButtonActionPerformed(evt);
            }
        });

        hapusParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        hapusParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        hapusParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car1.png"))); // NOI18N
        hapusParkirButton.setText("Hapus Parkir");
        hapusParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusParkirButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-Interface-Logout-icon-1.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel2.setText("Cari Nomor Kendaraan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(berandaAdminButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(selesaiParkirButton, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(hapusParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(berandaAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selesaiParkirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keluarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarTableMouseClicked
        // TODO add your handling code here:
        String nomorKendaraan = keluarTable.getValueAt(keluarTable.getSelectedRow(), keluarTable.getSelectedColumn()).toString();
        if (nomorKendaraan.equals("")) {
            Image error = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/errorImage.png"));
            ImageIcon errorImage = new ImageIcon(error);
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Errors", 1, (Icon) errorImage);
        } else {
            try {
                // TODO add your handling code here:
                int berhasil;
                berhasil = Database.getInstance().keluar(nomorKendaraan);
                if (berhasil == 0) {
                    Image error = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/errorImage.png"));
                    ImageIcon errorImage = new ImageIcon(error);
                    JOptionPane.showMessageDialog(null, "Nomor kendaraan tidak ditemukan, ulangi!", "Errors", 1, (Icon) errorImage);
                } else {
                    contentScrollPane.setViewportView(new KeluarParkir(contentScrollPane));
                }
            } catch (ParseException ex) {
                Logger.getLogger(KeluarParkir.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(KeluarParkir.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_keluarTableMouseClicked

    private void berandaAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaAdminButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new MenuAdmin(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(KeluarParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_berandaAdminButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new HapusParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    private void selesaiParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiParkirButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new SelesaiParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(KeluarParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selesaiParkirButtonActionPerformed

    private void hapusParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusParkirButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new HapusParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusParkirButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new LoginAdmin(contentScrollPane));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton berandaAdminButton;
    private javax.swing.JButton hapusParkirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable keluarTable;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton selesaiParkirButton;
    // End of variables declaration//GEN-END:variables
}
