/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Dwinanda
 */
public class LoginUmum extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;

    /**
     * Creates new form LoginCivitas
     */
    public LoginUmum(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        berandaParkirButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomorKendaraanTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        jenisKendaraanComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginUmumButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(243, 255, 243));

        berandaParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        berandaParkirButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        berandaParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        berandaParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet.gif"))); // NOI18N
        berandaParkirButton.setText("Beranda");
        berandaParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaParkirButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SISTEM MANAJEMEN PARKIR");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("POLITEKNIK STATISTIKA STIS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stiskecil.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Login Umum", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N

        nomorKendaraanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorKendaraanTextFieldActionPerformed(evt);
            }
        });

        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        jenisKendaraanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roda 2", "Roda 4" }));

        jLabel2.setText("Nama");

        jLabel5.setText("Nomor Kendaraan");

        loginUmumButton.setBackground(new java.awt.Color(51, 51, 255));
        loginUmumButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        loginUmumButton.setForeground(new java.awt.Color(255, 255, 255));
        loginUmumButton.setText("Masuk");
        loginUmumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUmumButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenis Kendaraan");

        jScrollPane1.setBackground(new java.awt.Color(213, 228, 234));

        keteranganTextArea.setEditable(false);
        keteranganTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        keteranganTextArea.setRows(5);
        keteranganTextArea.setText("Ket. Harga Parkir: \nRoda 2 \t: Rp2000/Jam\nRoda 4 \t: Rp4000/Jam");
        jScrollPane1.setViewportView(keteranganTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginUmumButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nomorKendaraanTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisKendaraanComboBox, 0, 154, Short.MAX_VALUE))))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomorKendaraanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jenisKendaraanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginUmumButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(118, 118, 118)
                .addComponent(berandaParkirButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(berandaParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jLabel9))
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void loginUmumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUmumButtonActionPerformed
        // TODO add your handling code here:        
        String nama = namaTextField.getText();
        String nomorKendaraan = nomorKendaraanTextField.getText();
        String jenisKendaraan = jenisKendaraanComboBox.getSelectedItem().toString();
        if (nama.equals("") || nomorKendaraan.equals("") || jenisKendaraan.equals("")) {
            Image error = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/errorImage.png"));
            ImageIcon errorImage = new ImageIcon(error);
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Errors", 1, (Icon) errorImage);
        } else {

            try {
                int duplikat = Database.getInstance().cekDuplikatUmum(nama, nomorKendaraan);
                if (duplikat == 0) {
                    try {
                        Database.getInstance().entriMasukParkirUmum(nama, nomorKendaraan, jenisKendaraan);
                        contentScrollPane.setViewportView(new BerandaParkir(contentScrollPane));
                    } catch (SQLException ex) {
                        Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    Image error = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/errorImage.png"));
                    ImageIcon errorImage = new ImageIcon(error);
                    JOptionPane.showMessageDialog(null, "Gagal Registrasi Karena Data Sudah Tersedia di Sistem, Harap Diulang Kembali!", "Errors", 1, (Icon) errorImage);
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginUmumButtonActionPerformed

    private void nomorKendaraanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorKendaraanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorKendaraanTextFieldActionPerformed

    private void berandaParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaParkirButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new BerandaParkir(contentScrollPane));
    }//GEN-LAST:event_berandaParkirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton berandaParkirButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisKendaraanComboBox;
    private javax.swing.JTextArea keteranganTextArea;
    private javax.swing.JButton loginUmumButton;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField nomorKendaraanTextField;
    // End of variables declaration//GEN-END:variables
}
