/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.Connection;

/**
 *
 * @author hanief
 */
public class LoginCivitas extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;

    /**
     * Creates new form LoginCivitas
     */
    public LoginCivitas(JScrollPane contentScrollPane) {
        this.contentScrollPane = contentScrollPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        berandaParkirButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jenisKendaraanComboBox = new javax.swing.JComboBox<>();
        loginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomorKendaraanTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keteranganTextArea = new javax.swing.JTextArea();
        nomorPengenalTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 255, 243));

        berandaParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        berandaParkirButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        berandaParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        berandaParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet.gif"))); // NOI18N
        berandaParkirButton.setText("Beranda");
        berandaParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaParkirButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Login Civitas Akademika", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N

        jenisKendaraanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roda 2", "Roda 4" }));

        loginButton.setBackground(new java.awt.Color(51, 51, 255));
        loginButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Jenis Kendaraan");

        jLabel4.setText("Belum memiliki akun?");

        nomorKendaraanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorKendaraanTextFieldActionPerformed(evt);
            }
        });

        passwordPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPasswordFieldActionPerformed(evt);
            }
        });

        registerButton.setForeground(new java.awt.Color(255, 0, 0));
        registerButton.setText("Register");
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Nomor Pengenal");

        keteranganTextArea.setEditable(false);
        keteranganTextArea.setBackground(new java.awt.Color(213, 218, 224));
        keteranganTextArea.setColumns(20);
        keteranganTextArea.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        keteranganTextArea.setRows(5);
        keteranganTextArea.setText("Ket. Harga Gratis\nNomor Pengenal: \nDosen \t: NIDN\nMahasiswa \t: NIM\nPegawai \t: Nomor Pegawai");
        jScrollPane1.setViewportView(keteranganTextArea);

        nomorPengenalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorPengenalTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Nomor Kendaraan");

        jLabel3.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorKendaraanTextField)
                            .addComponent(passwordPasswordField)
                            .addComponent(nomorPengenalTextField)
                            .addComponent(jenisKendaraanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(loginButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerButton)
                        .addGap(102, 102, 102))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomorPengenalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomorKendaraanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jenisKendaraanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(registerButton))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SISTEM MANAJEMEN PARKIR");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("POLITEKNIK STATISTIKA STIS");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stiskecil.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(127, 127, 127)
                        .addComponent(berandaParkirButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(berandaParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomorPengenalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorPengenalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorPengenalTextFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String nomorPengenal = nomorPengenalTextField.getText();
        String password = passwordPasswordField.getText();
        String jenisKendaraan = jenisKendaraanComboBox.getSelectedItem().toString();
        String nomorKendaraan = nomorKendaraanTextField.getText();

        if (nomorPengenal.equals("") || password.equals("") || jenisKendaraan.equals("") || nomorKendaraan.equals("")) {
            Image error = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/errorImage.png"));
            ImageIcon errorImage = new ImageIcon(error);
            JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!", "Errors", 1, (Icon) errorImage);
        } else {
            Connection conn = null;
            try {
                // TODO add your handling code here:
                conn = Database.getInstance().getConnection();
                int itungan = Database.getInstance().loginAnggota(nomorPengenal, password);
                if (itungan == 1) {
                    Database.getInstance().entriMasukParkirAnggota(nomorPengenal, nomorKendaraan, jenisKendaraan);
                    contentScrollPane.setViewportView(new BerandaParkir(contentScrollPane));
                } else {
                    Image error = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/errorImage.png"));
                    ImageIcon errorImage = new ImageIcon(error);
                    JOptionPane.showMessageDialog(null, "Login Gagal, Harap Diulang Kembali!", "Errors", 1, (Icon) errorImage);
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginCivitas.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginCivitas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new RegisterPanel(contentScrollPane));
    }//GEN-LAST:event_registerButtonActionPerformed

    private void nomorKendaraanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorKendaraanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorKendaraanTextFieldActionPerformed

    private void passwordPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPasswordFieldActionPerformed

    private void berandaParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaParkirButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new BerandaParkir(contentScrollPane));
    }//GEN-LAST:event_berandaParkirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton berandaParkirButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisKendaraanComboBox;
    private javax.swing.JTextArea keteranganTextArea;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField nomorKendaraanTextField;
    private javax.swing.JTextField nomorPengenalTextField;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
