/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import java.sql.SQLException;
import javax.swing.JScrollPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dwinanda
 */
public class MenuAdmin extends javax.swing.JPanel {
private JScrollPane contentScrollPane;
    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin(JScrollPane contentScrollPane) throws SQLException {
        this.contentScrollPane = contentScrollPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        keluarParkirButton = new javax.swing.JButton();
        selesaiParkirButton = new javax.swing.JButton();
        hapusParkirButton = new javax.swing.JButton();
        berandaAdminButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 255, 243));

        logoutButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-Interface-Logout-icon-1.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Menu Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N

        keluarParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        keluarParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        keluarParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        keluarParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mail-icon-1.png"))); // NOI18N
        keluarParkirButton.setText("Keluar Parkir");
        keluarParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarParkirButtonActionPerformed(evt);
            }
        });

        selesaiParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        selesaiParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        selesaiParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        selesaiParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/g11.png"))); // NOI18N
        selesaiParkirButton.setText("Selesai Parkir");
        selesaiParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiParkirButtonActionPerformed(evt);
            }
        });

        hapusParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        hapusParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        hapusParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car1.png"))); // NOI18N
        hapusParkirButton.setText("Hapus Parkir");
        hapusParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusParkirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keluarParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selesaiParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keluarParkirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selesaiParkirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusParkirButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        berandaAdminButton.setBackground(new java.awt.Color(0, 0, 0));
        berandaAdminButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        berandaAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        berandaAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet.gif"))); // NOI18N
        berandaAdminButton.setText("Beranda");
        berandaAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(berandaAdminButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(berandaAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hapusParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusParkirButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new HapusParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusParkirButtonActionPerformed

    private void keluarParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarParkirButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new KeluarParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_keluarParkirButtonActionPerformed

    private void selesaiParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiParkirButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new SelesaiParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selesaiParkirButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new LoginAdmin(contentScrollPane));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void berandaAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaAdminButtonActionPerformed
    try {
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new MenuAdmin(contentScrollPane));
    } catch (SQLException ex) {
        Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_berandaAdminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton berandaAdminButton;
    private javax.swing.JButton hapusParkirButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluarParkirButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton selesaiParkirButton;
    // End of variables declaration//GEN-END:variables
}
