/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Model.Selesai;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.layout.property.UnitValue;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author Dwinanda
 */
public class SelesaiParkir extends javax.swing.JPanel {

    private JScrollPane contentScrollPane;
    private DefaultTableModel tableModel;

    /**
     * Creates new form Selesai
     */
    public SelesaiParkir(JScrollPane contentScrollPane) throws SQLException {
        this.contentScrollPane = contentScrollPane;
        initComponents();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonCSVExport = new javax.swing.JButton();
        buttonPDFExport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jumlahPengunjung = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        totalBiayaOutput = new javax.swing.JTextField();
        summaryButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        selesaiTable = new javax.swing.JTable();
        berandaAdminButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        keluarParkirButton = new javax.swing.JButton();
        hapusParkirButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 255, 243));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Export", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        buttonCSVExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print-icon.png"))); // NOI18N
        buttonCSVExport.setText("CSV Report");
        buttonCSVExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCSVExportActionPerformed(evt);
            }
        });

        buttonPDFExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retrive.png"))); // NOI18N
        buttonPDFExport.setText("PDF Report");
        buttonPDFExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPDFExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonCSVExport)
                .addGap(18, 18, 18)
                .addComponent(buttonPDFExport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCSVExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPDFExport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Jumlah Pengunjung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jumlahPengunjung.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahPengunjung)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahPengunjung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total Biaya\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        totalBiayaOutput.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalBiayaOutput)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalBiayaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        summaryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/date.png"))); // NOI18N
        summaryButton.setText("Data Summary");
        summaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryButtonActionPerformed(evt);
            }
        });

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-edit-clear-icon.png"))); // NOI18N
        clearButton.setText("Clear Data");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tabel Parkir yang Selesai", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(0, 0, 102))); // NOI18N

        selesaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Nomor Kendaraan", "Waktu Masuk", "Waktu Keluar", "Durasi (menit)", "Biaya", "Civitas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(selesaiTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        berandaAdminButton.setBackground(new java.awt.Color(0, 0, 0));
        berandaAdminButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        berandaAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        berandaAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet.gif"))); // NOI18N
        berandaAdminButton.setText("Beranda");
        berandaAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                berandaAdminButtonActionPerformed(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(0, 0, 0));
        adminButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/r11.png"))); // NOI18N
        adminButton.setText("Admin");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        keluarParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        keluarParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        keluarParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        keluarParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mail-icon-1.png"))); // NOI18N
        keluarParkirButton.setText("Keluar Parkir");
        keluarParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarParkirButtonActionPerformed(evt);
            }
        });

        hapusParkirButton.setBackground(new java.awt.Color(0, 0, 0));
        hapusParkirButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        hapusParkirButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusParkirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car1.png"))); // NOI18N
        hapusParkirButton.setText("Hapus Parkir");
        hapusParkirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusParkirButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-Interface-Logout-icon-1.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(summaryButton))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keluarParkirButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusParkirButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(adminButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(berandaAdminButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(berandaAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(summaryButton)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hapusParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keluarParkirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminButton)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCSVExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCSVExportActionPerformed
        // TODO add your handling code here:
        // Membuat file CSV
        try {
            // Menulis header
            try (FileWriter csvWriter = new FileWriter("ParkingData.csv")) {
                // Menulis header
                for (int i = 0; i < selesaiTable.getColumnCount(); i++) {
                    csvWriter.append(selesaiTable.getColumnName(i));
                    if (i < selesaiTable.getColumnCount() - 1) {
                        csvWriter.append(",");
                    }
                }
                csvWriter.append("\n");

                // Menulis data baris
                for (int i = 0; i < selesaiTable.getRowCount(); i++) {
                    for (int j = 0; j < selesaiTable.getColumnCount(); j++) {
                        csvWriter.append(selesaiTable.getValueAt(i, j).toString());
                        if (j < selesaiTable.getColumnCount() - 1) {
                            csvWriter.append(",");
                        }
                    }
                    csvWriter.append("\n");
                }

                csvWriter.flush();
            }

            JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke ParkingData.csv");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengekspor data.");
        }
    }//GEN-LAST:event_buttonCSVExportActionPerformed

    private void summaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryButtonActionPerformed
        // TODO add your handling code here:
        // Menghitung jumlah pengunjung
        int rowCount = selesaiTable.getRowCount();
        jumlahPengunjung.setText(String.valueOf(rowCount));

        // Menghitung total biaya
        double totalBiaya = 0;
        for (int i = 0; i < rowCount; i++) {
            double biaya = Double.parseDouble(selesaiTable.getValueAt(i, 5).toString());
            totalBiaya += biaya;
        }
        totalBiayaOutput.setText(String.valueOf(totalBiaya));
    }//GEN-LAST:event_summaryButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus semua data parkir?",
                "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Database.getInstance().clearSelesaiData();
                JOptionPane.showMessageDialog(this, "Data parkir berhasil dihapus", "Pemberitahuan", JOptionPane.INFORMATION_MESSAGE);

                // Memuat ulang data ke dalam tabel setelah penghapusan
                loadTableData(); // Panggil loadTableData() di sini
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data parkir", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void berandaAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_berandaAdminButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new MenuAdmin(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(SelesaiParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_berandaAdminButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new MenuAdmin(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    private void keluarParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarParkirButtonActionPerformed
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new KeluarParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_keluarParkirButtonActionPerformed

    private void buttonPDFExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPDFExportActionPerformed
        try {
            exportToPDF();
        } catch (Exception e) {
            Logger.getLogger(SelesaiParkir.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Failed to export to PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonPDFExportActionPerformed

    private void hapusParkirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusParkirButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            contentScrollPane.setViewportView(new HapusParkir(contentScrollPane));
        } catch (SQLException ex) {
            Logger.getLogger(HapusParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusParkirButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new LoginAdmin(contentScrollPane));
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void loadTableData() {
        DefaultTableModel dtm = (DefaultTableModel) selesaiTable.getModel();
        // Refresh table
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }

        try {
            List<Selesai> selesaiList = Database.getInstance().loadTableDataSelesai(); // Assuming loadTableDataSelesai() returns List<Selesai>

            // Fill the table
            for (Selesai selesai : selesaiList) {
                dtm.addRow(new Object[]{
                    selesai.getNama(),
                    selesai.getNomorKendaraan(),
                    selesai.getWaktuMasuk(),
                    selesai.getWaktuKeluar(),
                    selesai.getDurasi(),
                    selesai.getBiaya(),
                    selesai.getCivitas()
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data", "Gagal", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace(); // Print stack trace for debugging
        }
    }

    private void exportToPDF() throws IOException, SQLException {
        // Initialize PDF writer and document
        PdfWriter writer = new PdfWriter("ParkingData.pdf");
        PdfDocument pdf = new PdfDocument(writer);
        Document document = new Document(pdf);

        // Add title to the PDF
        Paragraph title = new Paragraph("Parking Data Report");
        title.setFontSize(18);
        title.setBold();
        title.setTextAlignment(TextAlignment.CENTER);
        document.add(title);

        // Create a table
        Table table = new Table(selesaiTable.getColumnCount());
        // Set table width to 100% of page width
        table.setWidth(UnitValue.createPercentValue(100));

        // Add table headers
        for (int i = 0; i < selesaiTable.getColumnCount(); i++) {
            Cell header = new Cell().add(new Paragraph(selesaiTable.getColumnName(i)));
            table.addHeaderCell(header);
        }

        // Add table rows
        DefaultTableModel model = (DefaultTableModel) selesaiTable.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                table.addCell(model.getValueAt(row, col).toString());
            }
        }

        // Add the table to the document
        document.add(table);

        // Close document
        document.close();

        JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke ParkingData.pdf");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton berandaAdminButton;
    private javax.swing.JButton buttonCSVExport;
    private javax.swing.JButton buttonPDFExport;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton hapusParkirButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jumlahPengunjung;
    private javax.swing.JButton keluarParkirButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTable selesaiTable;
    private javax.swing.JButton summaryButton;
    private javax.swing.JTextField totalBiayaOutput;
    // End of variables declaration//GEN-END:variables
}
